/**
 * Series Routes
 *
 * Series/Story Bible, episodes, rap battles, music prompt generation.
 */

import { Router } from 'express';
import { audioIntelligence } from '../services/audio-intelligence';
import { existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { authMiddleware } from '../middleware/auth.js';
import { uploadMusic, musicDir } from './shared/multer-configs';
import { storage } from '../storage';
import { storyGenerator } from '../services/story-generator';
import { openaiService } from '../services/openai-service';
import { insertJobSchema, insertSeriesSchema, updateSeriesSchema, insertEpisodeSchema, updateEpisodeSchema } from '@shared/schema';
import { saveBase64Image } from './shared/helpers';


const router = Router();




  // ============ SERIES (Story Bible) ENDPOINTS ============

  // Create a new series from person, place, thing (or auto-discover from time period)
  router.post('/series/generate', authMiddleware, async (req, res) => {
    try {
      const { person, place, thing, genre, tone, timePeriod, isHistoricalFigure, additionalContext } = req.body;

      // Allow auto-discovery mode: historical figure + time period without person/place/thing
      const isAutoDiscovery = isHistoricalFigure && timePeriod && !person && !place && !thing;

      if (!isAutoDiscovery && (!person || !place || !thing)) {
        return res.status(400).json({
          success: false,
          error:
            'Person, place, and thing are required (or use Historical Figure mode with a time period for auto-discovery)',
        });
      }

      if (isAutoDiscovery) {
        console.log(`📚 Generating Story Bible (Auto-Discovery from ${timePeriod})...`);
      } else {
        console.log('📚 Generating Story Bible...');
      }

      const storyBible = await storyGenerator.generateStoryBible({
        person: person || '',
        place: place || '',
        thing: thing || '',
        genre,
        tone,
        timePeriod,
        isHistoricalFigure,
        additionalContext,
      });

      // Auto-generate lyrics for Episode 1 based on real historical events BEFORE creating series
      let autoGeneratedLyrics = null;
      const generatedSongs: Array<{
        episodeNumber: number;
        episodeTitle: string;
        style: string;
        lyrics: string;
        tags: string[];
        synopsis?: string;
        createdAt: string;
      }> = [];

      if (storyBible.episodeConcepts && storyBible.episodeConcepts.length > 0) {
        console.log('🎵 Auto-generating lyrics based on historical events...');
        try {
          const firstEpisode = storyBible.episodeConcepts[0];
          const musicPrompt = await storyGenerator.generateMusicPrompt(
            {
              title: storyBible.title,
              protagonist: storyBible.protagonist,
              antagonist: storyBible.antagonist,
              setting: storyBible.setting,
              storyArc: storyBible.storyArc,
              macguffin: storyBible.macguffin,
              supportingCharacters: storyBible.supportingCharacters,
              isHistorical: isHistoricalFigure,
              historicalNote: (storyBible as any).historicalNote,
            },
            1, // Episode 1
            {
              theme: 'origin' as const,
              conflict: firstEpisode.mainConflict || storyBible.storyArc.conflict,
              location: storyBible.setting.locations?.[0]?.name || storyBible.setting.name,
              emotionalJourney: firstEpisode.emotionalArc || 'doubt to determination',
              musicStyle: 'epic_orchestral' as const,
              tempo: 'medium' as const,
              mood: 'dramatic' as const,
            },
          );
          autoGeneratedLyrics = {
            episodeTitle: firstEpisode.title,
            sunoPrompt: musicPrompt.sunoPrompt,
            episodeContext: musicPrompt.episodeContext,
            recommendedDuration: musicPrompt.recommendedDuration,
          };

          // Store song in generatedSongs array
          generatedSongs.push({
            episodeNumber: 1,
            episodeTitle: firstEpisode.title,
            style: musicPrompt.sunoPrompt.style,
            lyrics: musicPrompt.sunoPrompt.lyrics,
            tags: musicPrompt.sunoPrompt.tags,
            synopsis: musicPrompt.episodeContext?.synopsis,
            createdAt: new Date().toISOString(),
          });

          console.log('   ✅ Auto-generated lyrics for Episode 1!');
        } catch (lyricsError) {
          console.error('   ⚠️ Failed to auto-generate lyrics:', lyricsError);
        }
      }

      const seriesData = insertSeriesSchema.parse({
        userId: req.user!.id,
        title: storyBible.title,
        protagonist: storyBible.protagonist,
        antagonist: storyBible.antagonist,
        setting: storyBible.setting,
        macguffin: storyBible.macguffin,
        storyArc: storyBible.storyArc,
        supportingCharacters: storyBible.supportingCharacters,
        visualStyle: storyBible.visualStyle,
        generatedSongs: generatedSongs.length > 0 ? generatedSongs : undefined,
      });

      let series = await storage.createSeries(seriesData);

      // Auto-generate character profiles for protagonist and antagonist
      const characterProfiles: { protagonist?: any; antagonist?: any } = {};

      try {
        console.log('🎨 Auto-generating character profile images...');

        const visualStyleDesc = storyBible.visualStyle?.cinematicStyle || 'cinematic portrait';

        const characterImages = await openaiService.generateCharacterImages(
          {
            name: storyBible.protagonist.name,
            description: storyBible.protagonist.description,
            traits: storyBible.protagonist.traits || [],
          },
          {
            name: storyBible.antagonist?.name || 'Antagonist',
            description: storyBible.antagonist?.description || 'A formidable adversary',
            traits: storyBible.antagonist?.traits || [],
          },
          visualStyleDesc,
        );

        // Save protagonist image and create profile
        const protagImageUrl = saveBase64Image(characterImages.protagonist.imageBase64, 'protagonist');
        const protagProfile = await storage.createCharacterProfile({
          name: storyBible.protagonist.name,
          refImageUrl: protagImageUrl,
          basePrompt: characterImages.protagonist.prompt,
          priority: 3.0, // Main character
        });
        characterProfiles.protagonist = protagProfile;
        console.log(`   ✅ Created protagonist profile: ${protagProfile.name} (${protagProfile.id})`);

        // Save antagonist image and create profile
        const antagImageUrl = saveBase64Image(characterImages.antagonist.imageBase64, 'antagonist');
        const antagProfile = await storage.createCharacterProfile({
          name: storyBible.antagonist?.name || 'Antagonist',
          refImageUrl: antagImageUrl,
          basePrompt: characterImages.antagonist.prompt,
          priority: 2.0, // Active side character
        });
        characterProfiles.antagonist = antagProfile;
        console.log(`   ✅ Created antagonist profile: ${antagProfile.name} (${antagProfile.id})`);

        // Update series with character profile IDs
        const updatedProtagonist = {
          ...storyBible.protagonist,
          characterProfileId: protagProfile.id,
        };
        const updatedAntagonist = {
          ...storyBible.antagonist,
          characterProfileId: antagProfile.id,
        };

        series =
          (await storage.updateSeries(series.id, {
            protagonist: updatedProtagonist,
            antagonist: updatedAntagonist,
          })) || series;

        console.log('✅ Character profiles linked to series!');
      } catch (charError: any) {
        console.error('⚠️ Failed to auto-generate character profiles:', charError.message);
        // Continue without character profiles - they can be added manually later
      }

      res.json({
        success: true,
        data: series,
        episodeConcepts: storyBible.episodeConcepts,
        autoGeneratedLyrics,
        characterProfiles: Object.keys(characterProfiles).length > 0 ? characterProfiles : undefined,
      });
    } catch (error: any) {
      console.error('Story generation error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to generate story bible',
      });
    }
  });


  // List all series
  router.get('/series', authMiddleware, async (req, res) => {
    try {
      const allSeries = await storage.listSeries();
      const userSeries = allSeries.filter((s) => !(s as any).userId || (s as any).userId === req.user!.id);
      res.json({ success: true, data: userSeries });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to list series',
      });
    }
  });


  // Get single series
  router.get('/series/:id', authMiddleware, async (req, res) => {
    try {
      const series = await storage.getSeries(req.params.id);
      if (!series) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }
      if ((series as any).userId && (series as any).userId !== req.user!.id) {
        return res.status(403).json({ success: false, error: 'Unauthorized' });
      }
      res.json({ success: true, data: series });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to get series',
      });
    }
  });


  // Update series
  router.patch('/series/:id', authMiddleware, async (req, res) => {
    try {
      const existingSeries = await storage.getSeries(req.params.id);
      if (!existingSeries) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }
      if ((existingSeries as any).userId && (existingSeries as any).userId !== req.user!.id) {
        return res.status(403).json({ success: false, error: 'Unauthorized' });
      }
      const validatedData = updateSeriesSchema.parse(req.body);
      const series = await storage.updateSeries(req.params.id, validatedData);
      res.json({ success: true, data: series });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to update series',
      });
    }
  });


  // Delete series
  router.delete('/series/:id', authMiddleware, async (req, res) => {
    try {
      const existingSeries = await storage.getSeries(req.params.id);
      if (!existingSeries) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }
      if ((existingSeries as any).userId && (existingSeries as any).userId !== req.user!.id) {
        return res.status(403).json({ success: false, error: 'Unauthorized' });
      }
      await storage.deleteSeries(req.params.id);
      res.json({ success: true });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to delete series',
      });
    }
  });


  // ============ MUSIC PROMPT GENERATOR (SUNO WORKFLOW) ============

  // Generate music prompt for Suno - Step 1 of the workflow
  router.post('/series/:seriesId/generate-music-prompt', async (req, res) => {
    try {
      const { seriesId } = req.params;
      const { theme, conflict, location, emotionalJourney, musicStyle, tempo, mood } = req.body;

      // Validate required fields
      if (!theme || !conflict || !musicStyle || !tempo || !mood) {
        return res.status(400).json({
          success: false,
          error: 'Missing required fields: theme, conflict, musicStyle, tempo, mood',
        });
      }

      const series = await storage.getSeries(seriesId);
      if (!series) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }

      const latestEpisode = await storage.getLatestEpisode(seriesId);
      const episodeNumber = (latestEpisode?.episodeNumber || 0) + 1;

      console.log('🎵 Generating Music Prompt for Suno...');
      const musicPrompt = await storyGenerator.generateMusicPrompt(
        series as any,
        episodeNumber,
        {
          theme,
          conflict,
          location: location || series.setting?.name || 'unknown location',
          emotionalJourney: emotionalJourney || 'struggle to triumph',
          musicStyle,
          tempo,
          mood,
        },
        latestEpisode?.synopsis,
      );

      // Save generated song to series for the Songs tab
      const existingSongs = (series as any).generatedSongs || [];
      const newSong = {
        episodeNumber,
        episodeTitle: musicPrompt.episodeContext?.title || `Episode ${episodeNumber}`,
        style: musicPrompt.sunoPrompt.style,
        lyrics: musicPrompt.sunoPrompt.lyrics,
        tags: musicPrompt.sunoPrompt.tags,
        synopsis: musicPrompt.episodeContext?.synopsis,
        createdAt: new Date().toISOString(),
      };

      await storage.updateSeries(seriesId, {
        generatedSongs: [...existingSongs, newSong],
      });

      res.json({
        success: true,
        data: {
          seriesId,
          seriesTitle: series.title,
          episodeNumber,
          musicPrompt,
        },
      });
    } catch (error: any) {
      console.error('Music prompt generation error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to generate music prompt',
      });
    }
  });


  // Quick Episode Generator - Generate complete episode package
  router.post('/series/:seriesId/quick-episode', async (req, res) => {
    try {
      const { seriesId } = req.params;
      const { theme, conflict, location, emotionalJourney, musicStyle, tempo, mood } = req.body;

      if (!theme || !conflict || !musicStyle || !tempo || !mood) {
        return res.status(400).json({
          success: false,
          error: 'Missing required fields: theme, conflict, musicStyle, tempo, mood',
        });
      }

      const series = await storage.getSeries(seriesId);
      if (!series) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }

      const latestEpisode = await storage.getLatestEpisode(seriesId);
      const episodeNumber = (latestEpisode?.episodeNumber || 0) + 1;

      console.log('⚡ Quick Episode Generator...');
      const quickEpisode = await storyGenerator.generateQuickEpisode(
        series as any,
        episodeNumber,
        {
          theme,
          conflict,
          location: location || series.setting?.name || 'unknown location',
          emotionalJourney: emotionalJourney || 'struggle to triumph',
          musicStyle,
          tempo,
          mood,
        },
        latestEpisode?.synopsis,
      );

      res.json({
        success: true,
        data: {
          seriesId,
          seriesTitle: series.title,
          episodeNumber,
          ...quickEpisode,
        },
      });
    } catch (error: any) {
      console.error('Quick episode generation error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to generate quick episode',
      });
    }
  });


  // ============ RAP BATTLE GENERATOR ============

  // Get available vocal/production style options for battle generation
  router.get('/battle-styles', async (req, res) => {
    try {
      const { getAvailableStyleOptions } = await import('../services/rap-battle-generator');
      const options = getAvailableStyleOptions();
      res.json({ success: true, data: options });
    } catch (error: any) {
      console.error('Error getting battle style options:', error);
      res.status(500).json({ success: false, error: error.message });
    }
  });


  // Generate a rap battle script (preview only, doesn't create episode)
  router.post('/series/:seriesId/rap-battle', async (req, res) => {
    try {
      const { seriesId } = req.params;
      const {
        battleTheme,
        conflictType = 'power',
        musicStyle = 'aggressive trap, hard-hitting 808s, battle rap',
        productionStyle = 'hard_trap',
        antagonistVocalStyle = 'raw_rap',
        protagonistVocalStyle = 'raw_rap',
        antagonistTone = 'dismissive_cold',
        protagonistTone = 'rising_from_ashes',
        bpm = 140,
        // Engagement Engine options
        engagementPreset = 'viral_battle',
        engagementTriggers = [],
        viralStructure = 'hook_hold_payoff',
      } = req.body;

      const series = await storage.getSeries(seriesId);
      if (!series) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }

      if (!series.protagonist || !series.antagonist) {
        return res.status(400).json({
          success: false,
          error: 'Series must have both a protagonist and antagonist for rap battles',
        });
      }

      console.log(`🎤 Generating Rap Battle Script: ${series.protagonist.name} vs ${series.antagonist.name}`);
      console.log(`🎹 Production: ${productionStyle}, Vocals: ${antagonistVocalStyle}/${protagonistVocalStyle}`);
      console.log(`🎭 Tones: ${antagonistTone} vs ${protagonistTone}`);

      const { rapBattleGenerator } = await import('../services/rap-battle-generator');

      const protagonistChar = {
        name: series.protagonist.name,
        role: 'protagonist' as const,
        description: series.protagonist.description,
        traits: series.protagonist.traits || [],
        motivation: series.protagonist.motivation || '',
        backstory: series.protagonist.backstory || '',
        vocalStyleKey: protagonistVocalStyle,
        emotionalToneKey: protagonistTone,
      };

      const antagonistChar = {
        name: series.antagonist.name,
        role: 'antagonist' as const,
        description: series.antagonist.description,
        traits: series.antagonist.traits || [],
        motivation: series.antagonist.motivation || '',
        backstory: series.antagonist.backstory || '',
        vocalStyleKey: antagonistVocalStyle,
        emotionalToneKey: antagonistTone,
      };

      console.log(`🎯 Engagement: preset=${engagementPreset}, structure=${viralStructure}`);

      const battle = await rapBattleGenerator.generateRapBattle(
        protagonistChar,
        antagonistChar,
        series.setting?.name || 'epic confrontation arena',
        battleTheme || series.storyArc?.stakes || 'ultimate victory',
        {
          rounds: 4,
          barsPerVerse: 4,
          bpm: bpm,
          style: musicStyle,
          productionStyle,
          antagonistVocalStyle,
          protagonistVocalStyle,
          antagonistTone,
          protagonistTone,
          // Engagement Engine options
          engagementPreset,
          engagementTriggers,
          viralStructure,
        },
      );

      console.log(`✅ Rap Battle script generated: ${battle.title}`);

      res.json({
        success: true,
        data: {
          battleScript: {
            title: battle.title,
            synopsis: `An epic lyrical confrontation between ${series.protagonist.name} and ${series.antagonist.name}. ${battleTheme || 'Everything is on the line.'}`,
            rounds: battle.rounds.map((r) => ({
              roundNumber: r.roundNumber,
              roundType: r.roundType,
              performer: r.character,
              lyrics: r.lyrics,
              scene: r.scene,
            })),
            sunoStyle: battle.sunoStyle,
            cleanLyrics: battle.cleanLyrics,
            visualTheme: battle.visualTheme,
            hookMoment: battle.hookMoment,
            visualsJson: battle.visualsJson,
          },
          characterProfiles: {
            protagonist: series.protagonist.characterProfileId,
            antagonist: series.antagonist.characterProfileId,
          },
        },
      });
    } catch (error: any) {
      console.error('Rap battle script generation error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to generate rap battle script',
      });
    }
  });


  // Save a generated rap battle to a new episode
  router.post('/series/:seriesId/episodes/save-battle', async (req, res) => {
    try {
      const { seriesId } = req.params;
      const { battleScript, title: customTitle } = req.body;

      if (!battleScript) {
        return res.status(400).json({ success: false, error: 'Battle script is required' });
      }

      const series = await storage.getSeries(seriesId);
      if (!series) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }

      if (!series.protagonist || !series.antagonist) {
        return res.status(400).json({
          success: false,
          error: 'Series must have both a protagonist and antagonist',
        });
      }

      // Get the next episode number
      const latestEpisode = await storage.getLatestEpisode(seriesId);
      const episodeNumber = (latestEpisode?.episodeNumber || 0) + 1;

      console.log(`💾 Saving Rap Battle as Episode ${episodeNumber}: ${battleScript.title}`);

      // Convert battle script to battle data format for storage
      const battleData = {
        setting: series.setting?.name || 'Unknown location',
        stakes: series.storyArc?.stakes || 'Victory',
        visualTheme: battleScript.visualTheme || 'Epic confrontation between power and defiance.',
        hookMoment: battleScript.hookMoment || 'The knockout bar at Round 4 finale.',
        rounds: battleScript.rounds.map((r: any) => ({
          roundNumber: r.roundNumber,
          character: r.performer,
          role: r.performer === series.protagonist?.name ? 'protagonist' : 'antagonist',
          scene: r.scene,
          voiceTag:
            r.roundType === 'opener' || r.roundType === 'escalation'
              ? 'deep menacing vocals, cold, commanding'
              : 'raw emotional vocals, gritty, determined',
          lyrics: r.lyrics,
          mood:
            r.roundType === 'closer'
              ? 'triumphant, explosive'
              : r.roundType === 'escalation'
                ? 'intense, building'
                : 'determined',
          cameraMovement: 'dynamic tracking',
        })),
        sunoStyle: battleScript.sunoStyle,
        cleanLyrics: battleScript.cleanLyrics,
        visualsJson: battleScript.visualsJson || [],
      };

      // Create the episode
      const episode = await storage.createEpisode({
        seriesId,
        episodeNumber,
        title: customTitle || battleScript.title || `Rap Battle ${episodeNumber}`,
        episodeType: 'rap_battle',
        synopsis:
          battleScript.synopsis ||
          `Epic lyrical confrontation between ${series.protagonist.name} and ${series.antagonist.name}`,
        battleData,
        plotPoints: battleScript.rounds.map((r: any, idx: number) => ({
          order: idx + 1,
          description: `Round ${r.roundNumber}: ${r.performer}'s verse`,
          scene: r.scene,
          characters: [r.performer],
          emotionalBeat: r.roundType,
        })),
      });

      console.log(`✅ Rap Battle saved as Episode ${episodeNumber}`);

      res.json({
        success: true,
        data: {
          episode,
          message: `Rap battle saved as Episode ${episodeNumber}`,
        },
      });
    } catch (error: any) {
      console.error('Save rap battle error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to save rap battle',
      });
    }
  });


  // Generate a rap battle episode between protagonist and antagonist
  router.post('/series/:seriesId/episodes/generate-battle', async (req, res) => {
    try {
      const { seriesId } = req.params;
      const {
        setting, // Where the battle takes place
        stakes, // What's being fought for
        rounds = 4, // Number of rounds (default 4)
        barsPerVerse = 6, // Bars per verse
        bpm = 140, // Battle tempo
        style, // Optional style override
      } = req.body;

      const series = await storage.getSeries(seriesId);
      if (!series) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }

      // Ensure we have both protagonist and antagonist
      if (!series.protagonist || !series.antagonist) {
        return res.status(400).json({
          success: false,
          error: 'Series must have both a protagonist and antagonist for rap battles',
        });
      }

      const latestEpisode = await storage.getLatestEpisode(seriesId);
      const episodeNumber = (latestEpisode?.episodeNumber || 0) + 1;

      console.log(`🎤 Generating Rap Battle: ${series.protagonist.name} vs ${series.antagonist.name}`);

      // Import the rap battle generator
      const { rapBattleGenerator } = await import('../services/rap-battle-generator');

      // Build battle characters from series protagonist/antagonist
      const protagonistChar = {
        name: series.protagonist.name,
        role: 'protagonist' as const,
        description: series.protagonist.description,
        traits: series.protagonist.traits || [],
        motivation: series.protagonist.motivation || '',
        backstory: series.protagonist.backstory || '',
      };

      const antagonistChar = {
        name: series.antagonist.name,
        role: 'antagonist' as const,
        description: series.antagonist.description,
        traits: series.antagonist.traits || [],
        motivation: series.antagonist.motivation || '',
        backstory: series.antagonist.backstory || '',
      };

      // Generate the battle
      const battle = await rapBattleGenerator.generateRapBattle(
        protagonistChar,
        antagonistChar,
        setting || series.setting?.name || 'epic confrontation arena',
        stakes || series.storyArc?.stakes || 'ultimate victory',
        { rounds, barsPerVerse, bpm, style },
      );

      // Create the episode with battle data
      const episode = await storage.createEpisode({
        seriesId,
        episodeNumber,
        title: `${battle.title} - The Battle`,
        episodeType: 'rap_battle',
        synopsis: `An epic lyrical confrontation between ${series.protagonist.name} and ${series.antagonist.name}. ${stakes || 'Everything is on the line.'}`,
        battleData: battle,
        plotPoints: battle.rounds.map((round, idx) => ({
          order: idx + 1,
          description: `Round ${round.roundNumber}: ${round.character}'s verse`,
          scene: round.scene,
          characters: [round.character],
          emotionalBeat: round.mood,
        })),
        status: 'scripted',
      });

      // Save to generated songs for the Songs tab
      const existingSongs = (series as any).generatedSongs || [];
      const newSong = {
        episodeNumber,
        episodeTitle: `${battle.title} - The Battle`,
        style: battle.sunoStyle,
        lyrics: battle.cleanLyrics,
        tags: ['battle rap', 'trap', '140 BPM', 'cinematic'],
        synopsis: `Rap battle: ${series.protagonist.name} vs ${series.antagonist.name}`,
        createdAt: new Date().toISOString(),
        isBattle: true,
      };

      await storage.updateSeries(seriesId, {
        generatedSongs: [...existingSongs, newSong],
        episodeCount: episodeNumber,
      });

      console.log(`✅ Rap Battle episode ${episodeNumber} created!`);

      res.json({
        success: true,
        data: {
          episode,
          battle: {
            title: battle.title,
            setting: battle.setting,
            stakes: battle.stakes,
            rounds: battle.rounds,
            sunoStyle: battle.sunoStyle,
            cleanLyrics: battle.cleanLyrics,
            visualTheme: battle.visualTheme,
            hookMoment: battle.hookMoment,
            visualsJson: battle.visualsJson,
          },
          sunoPrompt: {
            style: battle.sunoStyle,
            lyrics: battle.cleanLyrics,
          },
        },
      });
    } catch (error: any) {
      console.error('Rap battle generation error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to generate rap battle',
      });
    }
  });


  // ============ EPISODE ENDPOINTS ============

  // List episodes for a series
  router.get('/series/:seriesId/episodes', async (req, res) => {
    try {
      const episodes = await storage.listEpisodes(req.params.seriesId);
      res.json({ success: true, data: episodes });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to list episodes',
      });
    }
  });


  // Create episode with music analysis - ONE CLICK GENERATION
  router.post('/series/:seriesId/episodes/generate', uploadMusic.single('music'), async (req, res) => {
    try {
      const { seriesId } = req.params;
      const {
        separateAudio,
        transcribeLyrics,
        userDescription,
        episodeType,
        battleScript,
        generationType,
        characterIds: characterIdsJson,
        videoMode,
        aspectRatio,
      } = req.body;

      const series = await storage.getSeries(seriesId);
      if (!series) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }

      const latestEpisode = await storage.getLatestEpisode(seriesId);
      const episodeNumber = (latestEpisode?.episodeNumber || 0) + 1;

      let audioAnalysis = null;
      let musicUrl = null;

      if (req.file) {
        console.log('🎵 Processing uploaded music...');
        musicUrl = `/api/music/${req.file.filename}`;

        const fullAnalysis = await audioIntelligence.analyzeFullAudio(req.file.path, {
          separateAudio: separateAudio === 'true',
          transcribeLyrics: transcribeLyrics === 'true',
          userDescription,
        });

        audioAnalysis = {
          duration: fullAnalysis.duration,
          tempo: fullAnalysis.musicIntelligence.tempo,
          mood: fullAnalysis.musicIntelligence.mood,
          energy: fullAnalysis.musicIntelligence.energy,
          sections: fullAnalysis.musicIntelligence.sections,
          lyrics: fullAnalysis.lyrics?.text,
          hasVocals: fullAnalysis.hasVocals,
        };
      }

      // Handle rap battle episodes with pre-generated battle script
      if (episodeType === 'rap_battle' && battleScript) {
        console.log(`🎤 Creating rap battle episode (${generationType || 'full'})...`);

        let parsedBattle;
        try {
          parsedBattle = typeof battleScript === 'string' ? JSON.parse(battleScript) : battleScript;
        } catch (e) {
          return res.status(400).json({ success: false, error: 'Invalid battle script format' });
        }

        // Parse character IDs if provided
        let characterIds: string[] = [];
        if (characterIdsJson) {
          try {
            characterIds = typeof characterIdsJson === 'string' ? JSON.parse(characterIdsJson) : characterIdsJson;
          } catch (e) {
            console.warn('Could not parse characterIds:', e);
          }
        }

        // Generate scenes from battle rounds
        const generatedScenes =
          parsedBattle.rounds?.map((round: any, idx: number) => ({
            order: idx + 1,
            prompt: `${round.roundType}: ${round.performer} - ${round.scene?.description || round.lyrics?.substring(0, 100)}`,
            environment: round.scene?.environment || 'Battle arena',
            mood: round.scene?.mood || 'intense',
            camera: round.scene?.cameraWork || 'dynamic tracking',
            lighting: round.scene?.lighting || 'dramatic stage lighting',
          })) || [];

        const genTypeLabel =
          generationType === 'protagonist'
            ? ` (${series.protagonist?.name || 'Protagonist'})`
            : generationType === 'antagonist'
              ? ` (${series.antagonist?.name || 'Antagonist'})`
              : '';

        const episodeData = insertEpisodeSchema.parse({
          seriesId,
          episodeNumber,
          title: parsedBattle.title + genTypeLabel,
          episodeType: 'rap_battle',
          synopsis:
            parsedBattle.synopsis || `Rap battle between ${series.protagonist?.name} and ${series.antagonist?.name}`,
          battleData: parsedBattle,
          plotPoints: generatedScenes.map((s: any, idx: number) => ({
            order: idx + 1,
            description: s.prompt,
          })),
          previousEpisodeSummary: latestEpisode?.synopsis,
          musicUrl,
          audioAnalysis,
          generatedScenes,
          videoMode: videoMode || 'veo',
          aspectRatio: aspectRatio || '9:16',
          status: 'scripted',
        });

        const episode = await storage.createEpisode(episodeData);

        // REMOVED AUTO-GENERATION: User must explicitly request video generation
        // Previously: If musicUrl was present, it would auto-start video generation
        // Now: Episode is saved, user can click "Generate Video" when ready
        console.log(`✅ Rap battle episode saved: ${episode.title} (${generatedScenes.length} scenes)`);
        console.log(`   ℹ️  Video generation NOT started automatically - use Generate Video button when ready`);

        return res.json({
          success: true,
          data: episode,
          message: `Rap battle episode "${parsedBattle.title}" created with ${generatedScenes.length} scenes. Use Generate Video when ready.`,
        });
      }

      // Standard episode generation flow
      console.log(`📝 Generating Episode ${episodeNumber} script...`);
      const episodeScript = audioAnalysis
        ? await storyGenerator.generateEpisodeFromMusic(
            series as any,
            episodeNumber,
            audioAnalysis,
            latestEpisode?.synopsis,
          )
        : await storyGenerator.generateEpisodeScript(series as any, episodeNumber, latestEpisode?.synopsis);

      const episodeData = insertEpisodeSchema.parse({
        seriesId,
        episodeNumber,
        title: episodeScript.title,
        synopsis: episodeScript.synopsis,
        plotPoints: episodeScript.plotPoints,
        previousEpisodeSummary: latestEpisode?.synopsis,
        musicUrl,
        audioAnalysis,
        generatedScenes: episodeScript.generatedScenes,
        status: 'scripted',
      });

      const episode = await storage.createEpisode(episodeData);

      res.json({
        success: true,
        data: episode,
        message: `Episode ${episodeNumber} created with ${episodeScript.generatedScenes?.length || 0} scenes`,
      });
    } catch (error: any) {
      console.error('Episode generation error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to generate episode',
      });
    }
  });


  // Generate video from episode
  router.post('/episodes/:episodeId/generate-video', async (req, res) => {
    try {
      const episode = await storage.getEpisode(req.params.episodeId);
      if (!episode) {
        return res.status(404).json({ success: false, error: 'Episode not found' });
      }

      const series = await storage.getSeries(episode.seriesId);
      if (!series) {
        return res.status(404).json({ success: false, error: 'Series not found' });
      }

      // Handle rap battles vs regular episodes differently
      const isRapBattle = episode.episodeType === 'rap_battle';
      let scenes: any[] = [];
      let scriptContent = '';

      if (isRapBattle && episode.battleData) {
        // For rap battles, use visualsJson for scenes and cleanLyrics for script
        const visualsJson = episode.battleData.visualsJson || [];
        const rounds = episode.battleData.rounds || [];

        // Performance action templates for each round - ensures characters are RAPPING not walking
        const getPerformanceAction = (roundIdx: number, characterName: string, isAntagonist: boolean): string => {
          const roundActions = [
            // Round 1: Antagonist opens with dominance
            isAntagonist
              ? `${characterName} RAPPING AGGRESSIVELY, standing atop elevated position, arms spread wide in dominance, face twisted with contempt, delivering opening verse with powerful hand gestures, chest puffed up, looking down at opponent`
              : `${characterName} RAPPING DEFIANTLY, stepping forward with fists clenched, pointing at opponent, chin raised, voice carrying power, building intensity`,
            // Round 2: Response with defiance
            isAntagonist
              ? `${characterName} RAPPING with controlled fury, pacing like a caged predator, calculated gestures, eyes locked on opponent, each word delivered with surgical precision`
              : `${characterName} RAPPING INTENSELY, stepping forward with explosive energy, pointing finger at opponent accusingly, body language showing rising confidence, voice booming`,
            // Round 3: Escalation - tension peaks
            isAntagonist
              ? `EXTREME CLOSE-UP of ${characterName} RAPPING WITH VISIBLE RAGE, composure cracking, grip tightening, veins visible, spitting bars with desperate intensity, sweat on brow`
              : `${characterName} RAPPING RELENTLESSLY, advancing toward opponent, jabbing finger rhythmically with each bar, crowd energy feeding their power, unstoppable momentum`,
            // Round 4: Finale - knockout
            isAntagonist
              ? `${characterName} RAPPING defensively, backing up, stumbling on words, dominance crumbling, fear in eyes as opponent approaches`
              : `${characterName} DELIVERING KNOCKOUT BARS, ascending triumphantly, arms raised in victory, opponent cowering, crowd explosion behind them, ultimate power moment`,
          ];
          return roundActions[Math.min(roundIdx, 3)] || roundActions[0];
        };

        // ALWAYS build scenes from rounds (primary source of truth for performer/role)
        // Use visualsJson only for supplementary visual metadata
        if (rounds.length > 0) {
          scenes = rounds.map((round: any, idx: number) => {
            // Get role directly from round data (authoritative source)
            const isAntagonist = round.role === 'antagonist';
            const characterName = round.character || (isAntagonist ? 'Antagonist' : 'Protagonist');
            const performanceAction = getPerformanceAction(idx, characterName, isAntagonist);

            // Get supplementary visual info from visualsJson if available
            const visualInfo = visualsJson[idx] || {};
            const camera = visualInfo.camera || round.cameraMovement || 'dynamic camera';
            const lighting = visualInfo.lighting || 'dramatic';
            const mood = visualInfo.mood || round.mood || 'intense';
            const environment = visualInfo.scene || round.scene || 'battle arena';

            // Combine performance action with environment
            const fullPrompt = `${performanceAction}. Environment: ${environment}. ${lighting} lighting, ${camera}. Mood: ${mood}. RAP BATTLE PERFORMANCE - character actively performing and rapping, not walking.`;

            return {
              sceneNumber: idx + 1,
              start: 0,
              end: 0,
              prompt: fullPrompt,
              cameraWork: camera,
              mood: mood,
              character: characterName,
              lyrics: round.lyrics || '',
            };
          });
        } else if (visualsJson.length > 0) {
          // Fallback to visualsJson if no rounds (shouldn't happen, but be safe)
          scenes = visualsJson.map((v: any, idx: number) => {
            const isAntagonist = v.section?.toLowerCase().includes('antagonist') || idx % 2 === 0;
            const characterName = v.character || (isAntagonist ? 'Antagonist' : 'Protagonist');
            const performanceAction = getPerformanceAction(idx, characterName, isAntagonist);

            const fullPrompt = `${performanceAction}. Environment: ${v.scene}. ${v.lighting} lighting, ${v.camera}. Mood: ${v.mood}. RAP BATTLE PERFORMANCE - character actively performing, not walking.`;

            return {
              sceneNumber: idx + 1,
              start: 0,
              end: 0,
              prompt: fullPrompt,
              cameraWork: v.camera || 'medium shot',
              mood: v.mood || 'intense',
              character: characterName,
              lyrics: '',
            };
          });
        }

        // For rap battles, use scene prompts as script content (NOT just lyrics)
        // This ensures the job-worker generates videos with the performance actions we specified
        scriptContent = scenes
          .map((s: any, idx: number) => {
            // Get lyrics from scene object (added above) or from rounds
            const lyrics = s.lyrics || rounds[idx]?.lyrics || '';

            // Only include lyrics section if we have actual lyrics
            const lyricsSection = lyrics.trim() ? `LYRICS:\n${lyrics}` : '';

            return `[SCENE ${idx + 1}]
VISUAL: ${s.prompt}
${lyricsSection}`.trim();
          })
          .join('\n\n---\n\n');

        // If no scene prompts, fall back to clean lyrics
        if (!scriptContent || scriptContent.length < 50) {
          scriptContent =
            episode.battleData.cleanLyrics || rounds.map((r: any) => r.lyrics).join('\n\n') || episode.synopsis;
        }

        // Log the prompts for debugging
        console.log(`🎤 Rap battle video: ${scenes.length} scenes with performance prompts`);
        scenes.forEach((s: any, i: number) => {
          console.log(`   Scene ${i + 1}: ${s.prompt.substring(0, 100)}...`);
        });
      } else {
        // Regular episode - use generatedScenes
        scenes = episode.generatedScenes || [];
        scriptContent = scenes.map((s: any) => s.prompt).join('\n\n');
      }

      // Validate we have content
      if (scenes.length === 0) {
        return res.status(400).json({
          success: false,
          error: 'No scenes found. Please ensure the episode has generated scenes or battle data.',
        });
      }

      if (!scriptContent || scriptContent.length < 10) {
        scriptContent = episode.synopsis || scenes.map((s: any) => s.prompt).join('\n\n');
      }

      // Check for music URL - required for video generation
      if (!episode.musicUrl) {
        return res.status(400).json({
          success: false,
          error: 'No music uploaded. Please upload music for this episode before generating video.',
        });
      }

      const characterIds = req.body.characterIds || [];

      // For rap battles, auto-add protagonist and antagonist character profiles
      if (isRapBattle && characterIds.length === 0) {
        if (series.protagonist?.characterProfileId) {
          characterIds.push(series.protagonist.characterProfileId);
        }
        if (series.antagonist?.characterProfileId) {
          characterIds.push(series.antagonist.characterProfileId);
        }
      }

      // Use video mode from episode or request, default to consistent if character profiles exist
      const mode = (episode as any).videoMode || (characterIds.length > 0 ? 'consistent' : 'veo');
      // Priority: request body > episode stored value > default to 9:16 for social media
      const selectedAspectRatio = req.body.aspectRatio || (episode as any).aspectRatio || '9:16';
      console.log(
        `🎬 Video generation: mode=${mode}, aspectRatio=${selectedAspectRatio}, characters=${characterIds.length}`,
      );

      // Parse post-processing options if provided
      let postProcessingOptions = null;
      if (req.body.postProcessing) {
        try {
          postProcessingOptions =
            typeof req.body.postProcessing === 'string' ? JSON.parse(req.body.postProcessing) : req.body.postProcessing;
          console.log(`🎬 Post-processing options:`, postProcessingOptions);
        } catch (e) {
          console.warn('Could not parse postProcessing options:', e);
        }
      }

      const jobData = insertJobSchema.parse({
        scriptName: `${series.title} - ${episode.title}`,
        scriptContent,
        mode,
        aspectRatio: selectedAspectRatio,
        musicUrl: episode.musicUrl,
        musicDescription: isRapBattle ? 'Rap battle soundtrack' : `Episode ${episode.episodeNumber} soundtrack`,
        audioDuration: episode.audioAnalysis?.duration?.toString(),
        characterProfileIds: characterIds,
        musicAnalysis: episode.audioAnalysis
          ? {
              bpm: episode.audioAnalysis.tempo,
              mood: episode.audioAnalysis.mood,
              structure: { sections: episode.audioAnalysis.sections },
              postProcessing: postProcessingOptions,
            }
          : postProcessingOptions
            ? { postProcessing: postProcessingOptions }
            : undefined,
      });

      const job = await storage.createJob(jobData);

      await storage.updateEpisode(episode.id, {
        jobId: job.id,
        status: 'generating',
      });

      res.json({
        success: true,
        data: { job, episode },
        message: `Video generation started for Episode ${episode.episodeNumber}`,
      });
    } catch (error: any) {
      console.error('Video generation error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to start video generation',
      });
    }
  });


  // Add music to existing episode (for saved rap battles that need music later)
  router.post('/episodes/:id/add-music', uploadMusic.single('music'), async (req, res) => {
    try {
      const episode = await storage.getEpisode(req.params.id);
      if (!episode) {
        return res.status(404).json({ success: false, error: 'Episode not found' });
      }

      if (!req.file) {
        return res.status(400).json({ success: false, error: 'Music file is required' });
      }

      console.log(`🎵 Adding music to episode: ${episode.title}`);

      // Move uploaded file to permanent location
      const fs = await import('fs');
      const path = await import('path');
      const musicFileName = `music_${Date.now()}_${Math.random().toString(36).substring(2, 8)}.mp3`;
      const musicDir = path.join(process.cwd(), 'attached_assets', 'music');
      const musicPath = path.join(musicDir, musicFileName);

      // Ensure music directory exists
      if (!fs.existsSync(musicDir)) {
        fs.mkdirSync(musicDir, { recursive: true });
      }

      fs.copyFileSync(req.file.path, musicPath);
      const musicUrl = `/api/music/${musicFileName}`;

      // Full audio analysis (includes duration)
      let audioAnalysis: any = { duration: 60 }; // fallback
      try {
        const { audioIntelligence } = await import('../services/audio-intelligence');
        console.log(`🎬 Analyzing music for episode...`);
        const fullAnalysis = await audioIntelligence.analyzeFullAudio(musicPath, {
          separateAudio: false,
          transcribeLyrics: false,
          userDescription: episode.synopsis,
        });

        audioAnalysis = {
          duration: fullAnalysis.duration,
          tempo: fullAnalysis.musicIntelligence.tempo,
          mood: fullAnalysis.musicIntelligence.mood,
          energy: fullAnalysis.musicIntelligence.energy,
          sections: fullAnalysis.musicIntelligence.sections,
        };
        console.log(`✅ Music analysis complete: ${audioAnalysis.duration}s, ${audioAnalysis.tempo} BPM`);
      } catch (analysisError) {
        console.warn('Audio analysis failed, using basic info:', analysisError);
      }

      // Update episode with music
      const updatedEpisode = await storage.updateEpisode(episode.id, {
        musicUrl,
        audioAnalysis,
      });

      res.json({
        success: true,
        data: updatedEpisode,
        message: `Music added to episode (${Math.round(audioAnalysis.duration || 0)}s)`,
      });
    } catch (error: any) {
      console.error('Add music error:', error);
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to add music to episode',
      });
    }
  });


  // Get single episode
  router.get('/episodes/:id', async (req, res) => {
    try {
      const episode = await storage.getEpisode(req.params.id);
      if (!episode) {
        return res.status(404).json({ success: false, error: 'Episode not found' });
      }
      res.json({ success: true, data: episode });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to get episode',
      });
    }
  });


  // Update episode
  router.patch('/episodes/:id', async (req, res) => {
    try {
      const validatedData = updateEpisodeSchema.parse(req.body);
      const episode = await storage.updateEpisode(req.params.id, validatedData);
      if (!episode) {
        return res.status(404).json({ success: false, error: 'Episode not found' });
      }
      res.json({ success: true, data: episode });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to update episode',
      });
    }
  });


  // Delete episode
  router.delete('/episodes/:id', async (req, res) => {
    try {
      await storage.deleteEpisode(req.params.id);
      res.json({ success: true });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        error: error.message || 'Failed to delete episode',
      });
    }
  });


export default router;
