import { initializeSecretsFromGCP } from './server/secret-manager-loader';
import { google } from 'googleapis';

const videoIds = ['sxTBOL8ByE8', 'ehO0ke8zt24', 'nUU7Rh1rTxg', 'cDJv0kbeyTU', 'R0X6RUJro8U', 'MN993V_lkbU'];

async function checkThumbnailStatus() {
  console.log('🔐 Loading secrets...');
  await initializeSecretsFromGCP();
  console.log('✅ Secrets loaded\n');

  const { youtubeUploadService } = await import('./server/services/youtube-upload-service');

  // Get the OAuth client
  const oauth2Client = (youtubeUploadService as any).oauth2Client;
  const youtube = google.youtube({ version: 'v3', auth: oauth2Client });

  console.log('🔍 Checking actual YouTube thumbnail data...\n');

  for (const videoId of videoIds) {
    console.log(`📺 Video: ${videoId}`);

    try {
      const response = await youtube.videos.list({
        part: ['snippet'],
        id: [videoId],
      });

      const video = response.data.items?.[0];

      if (!video || !video.snippet) {
        console.log('   ❌ Video not found\n');
        continue;
      }

      console.log(`   Title: ${video.snippet.title}`);
      console.log(`   Thumbnails in API response:`);

      if (video.snippet.thumbnails) {
        const thumbs = video.snippet.thumbnails;
        console.log(`      - default: ${thumbs.default ? '✅ ' + thumbs.default.url : '❌'}`);
        console.log(`      - medium: ${thumbs.medium ? '✅ ' + thumbs.medium.url : '❌'}`);
        console.log(`      - high: ${thumbs.high ? '✅ ' + thumbs.high.url : '❌'}`);
        console.log(`      - standard: ${thumbs.standard ? '✅ ' + thumbs.standard.url : '❌'}`);
        console.log(`      - maxres: ${thumbs.maxres ? '✅ ' + thumbs.maxres.url : '❌'}`);

        // Check if URL contains 'hqdefault' (auto-generated) or 'sddefault' (custom)
        if (thumbs.default?.url) {
          const isAutoGenerated =
            thumbs.default.url.includes('hqdefault') ||
            thumbs.default.url.includes('mqdefault') ||
            thumbs.default.url.includes('default.jpg');
          console.log(`   📸 Thumbnail type: ${isAutoGenerated ? '🤖 AUTO-GENERATED' : '✨ CUSTOM'}`);
        }
      } else {
        console.log('   ❌ No thumbnail data in API response');
      }

      console.log();
    } catch (error: any) {
      console.log(`   ❌ Error: ${error.message}\n`);
    }

    await new Promise((r) => setTimeout(r, 500));
  }

  // Check channel verification status
  console.log('\n🔍 Checking channel verification status...\n');
  try {
    const channelsResponse = await youtube.channels.list({
      part: ['status'],
      mine: true,
    });

    const channel = channelsResponse.data.items?.[0];
    if (channel?.status) {
      console.log('📋 Channel Status:');
      console.log(`   Long uploads enabled: ${channel.status.longUploadsStatus === 'allowed' ? '✅' : '❌'}`);
      console.log(`   Made for kids: ${channel.status.madeForKids ? '✅' : '❌'}`);

      // The key indicator for custom thumbnails
      if (channel.status.longUploadsStatus === 'allowed') {
        console.log('\n✅ Channel is verified - custom thumbnails should work');
      } else {
        console.log('\n⚠️  Channel may not be verified - custom thumbnails might not work');
        console.log('   To enable custom thumbnails:');
        console.log('   1. Go to https://www.youtube.com/verify');
        console.log('   2. Verify your phone number');
        console.log('   3. Wait 24 hours for verification to take effect\n');
      }
    }
  } catch (error: any) {
    console.log(`❌ Could not check channel status: ${error.message}`);
  }

  process.exit(0);
}

checkThumbnailStatus().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
