#!/bin/bash

echo "💰 Budget Dual Instance Setup - 2x n1-standard-8"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "📊 Your Choice:"
echo "   2x n1-standard-8 (8 vCPUs each)"
echo "   Total: 16 vCPUs, 60GB RAM, 2x Tesla T4"
echo "   Cost: $480/month ($240 × 2)"
echo "   Speedup: 2x faster than current"
echo "   Perfect for: Doubling throughput without breaking the bank"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "🚀 STEP 1: Keep Instance 1 As-Is (No Changes Needed!)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Your current ai-workspace is already n1-standard-8"
echo "✅ No downtime, no changes needed"
echo "✅ Just create the second instance!"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🚀 STEP 2: Create Instance 2 (ai-workspace-2)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "gcloud compute instances create ai-workspace-2 \\"
echo "  --zone=us-central1-a \\"
echo "  --project=unity-ai-1766877776 \\"
echo "  --machine-type=n1-standard-8 \\"
echo "  --accelerator=type=nvidia-tesla-t4,count=1 \\"
echo "  --boot-disk-size=200GB \\"
echo "  --boot-disk-type=pd-balanced \\"
echo "  --image-family=ubuntu-2204-lts \\"
echo "  --image-project=ubuntu-os-cloud \\"
echo "  --maintenance-policy=TERMINATE \\"
echo "  --metadata=install-nvidia-driver=True \\"
echo "  --scopes=cloud-platform"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🛠️  STEP 3: Set Up Instance 2 (After it's created)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Wait for instance to boot (~2 minutes), then SSH in:"
echo "gcloud compute ssh ai-workspace-2 --zone=us-central1-a --project=unity-ai-1766877776"
echo ""
echo "# Once inside ai-workspace-2, run these commands:"
echo "───────────────────────────────────────────────────────────────────"
echo ""
echo "# 1. Install Node.js 20"
echo "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
echo "sudo apt-get install -y nodejs"
echo ""
echo "# 2. Clone your repo (or copy files from instance 1)"
echo "cd /home/aaronishere2025"
echo "# Option A: Copy from instance 1"
echo "gcloud compute scp --recurse ai-workspace:/home/aaronishere2025 /home/aaronishere2025 --zone=us-central1-a"
echo ""
echo "# Option B: Git clone (if repo is on GitHub)"
echo "# git clone https://github.com/YOUR_USERNAME/unity-ai.git"
echo "# cd unity-ai"
echo ""
echo "# 3. Install dependencies"
echo "npm install"
echo ""
echo "# 4. Set up Python environment"
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo "pip install librosa numpy pydantic soundfile scipy opencv-python demucs torch"
echo ""
echo "# 5. Copy .env file from instance 1"
echo "# FROM YOUR LOCAL MACHINE (not in SSH):"
echo "gcloud compute scp ai-workspace:/home/aaronishere2025/.env ai-workspace-2:/home/aaronishere2025/.env --zone=us-central1-a"
echo ""
echo "# 6. Verify NVIDIA drivers installed"
echo "nvidia-smi"
echo ""
echo "# 7. Start the worker (NO FRONTEND on instance 2)"
echo "# Edit package.json to add a worker-only mode:"
echo 'NODE_ENV=production node dist/index.js &'
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🎯 SIMPLIFIED SETUP (Copy entire directory from instance 1)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# After instance 2 is created, from YOUR LOCAL MACHINE:"
echo ""
echo "# 1. Copy everything from instance 1 to instance 2"
echo "gcloud compute ssh ai-workspace --zone=us-central1-a --command=\"tar czf /tmp/unity-backup.tar.gz /home/aaronishere2025\""
echo "gcloud compute scp ai-workspace:/tmp/unity-backup.tar.gz /tmp/unity-backup.tar.gz --zone=us-central1-a"
echo "gcloud compute scp /tmp/unity-backup.tar.gz ai-workspace-2:/tmp/unity-backup.tar.gz --zone=us-central1-a"
echo "gcloud compute ssh ai-workspace-2 --zone=us-central1-a --command=\"cd / && sudo tar xzf /tmp/unity-backup.tar.gz\""
echo ""
echo "# 2. SSH into instance 2 and start the server"
echo "gcloud compute ssh ai-workspace-2 --zone=us-central1-a"
echo "cd /home/aaronishere2025"
echo "npm run dev &"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "✅ VERIFICATION"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "After both instances are running, check the jobs page:"
echo "http://localhost:8080/jobs"
echo ""
echo "You should see:"
echo "• Jobs being picked up by both instances"
echo "• Total parallel capacity: 16-20 jobs"
echo "• 2x faster throughput!"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "💰 COST BREAKDOWN"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Instance 1 (ai-workspace):     \$240/month"
echo "Instance 2 (ai-workspace-2):   \$240/month"
echo "───────────────────────────────────────────"
echo "Total:                         \$480/month"
echo ""
echo "Speedup: 2x faster (8 vCPUs → 16 vCPUs)"
echo "10-minute generation → ~5 minutes"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🎮 HOW LOAD BALANCING WORKS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. Queue 10 trap beats + 10 lofi beats = 20 jobs"
echo "2. Instance 1 picks up 10 jobs (queued → processing)"
echo "3. Instance 2 picks up 10 jobs (queued → processing)"
echo "4. Both process 8-10 jobs in parallel"
echo "5. All 20 jobs complete in ~5 minutes instead of 10!"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🚀 Ready to create instance 2? Copy the command above!"
echo "═══════════════════════════════════════════════════════════════════"
