#!/bin/bash

echo "🚀 Dual Instance Setup - Double CPU Power, Better Cost"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Current instance info
INSTANCE_NAME="ai-workspace"
ZONE="us-central1-a"
PROJECT="unity-ai-1766877776"
CURRENT_TYPE="n1-standard-8"

echo "📊 Current Setup:"
echo "   Instance: $INSTANCE_NAME"
echo "   Zone: $ZONE"
echo "   Machine Type: $CURRENT_TYPE (8 vCPUs)"
echo "   Cost: ~\$240/month"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🎯 DUAL INSTANCE STRATEGY"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "Option 1: 2x n2-highcpu-16 (RECOMMENDED) 🔥"
echo "────────────────────────────────────────────────────────────────────"
echo "   Per instance: 16 vCPUs, 16GB RAM, Tesla T4"
echo "   Total: 32 vCPUs, 32GB RAM, 2x Tesla T4"
echo "   Cost: \$300/month × 2 = \$600/month"
echo "   Speedup: 4x faster than current"
echo "   Savings: \$100/month vs single n2-highcpu-32"
echo ""

echo "Option 2: 2x n1-standard-8 (BUDGET)"
echo "────────────────────────────────────────────────────────────────────"
echo "   Per instance: 8 vCPUs, 30GB RAM, Tesla T4"
echo "   Total: 16 vCPUs, 60GB RAM, 2x Tesla T4"
echo "   Cost: \$240/month × 2 = \$480/month"
echo "   Speedup: 2x faster than current"
echo "   Savings: \$20/month vs single n2-standard-16"
echo ""

echo "Option 3: 2x n2-standard-8 (BALANCED)"
echo "────────────────────────────────────────────────────────────────────"
echo "   Per instance: 8 vCPUs, 32GB RAM, Tesla T4"
echo "   Total: 16 vCPUs, 64GB RAM, 2x Tesla T4"
echo "   Cost: \$200/month × 2 = \$400/month"
echo "   Speedup: 2.3x faster than current"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "📋 SETUP STEPS (Recommended: 2x n2-highcpu-16)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "Step 1: Upgrade existing instance (ai-workspace)"
echo "────────────────────────────────────────────────────────────────────"
echo "gcloud compute instances stop $INSTANCE_NAME --zone=$ZONE --project=$PROJECT"
echo "gcloud compute instances set-machine-type $INSTANCE_NAME --machine-type=n2-highcpu-16 --zone=$ZONE --project=$PROJECT"
echo "gcloud compute instances start $INSTANCE_NAME --zone=$ZONE --project=$PROJECT"
echo ""

echo "Step 2: Create second instance (ai-workspace-2)"
echo "────────────────────────────────────────────────────────────────────"
echo "# Clone the existing instance configuration"
echo "gcloud compute instances create ai-workspace-2 \\"
echo "  --zone=$ZONE \\"
echo "  --project=$PROJECT \\"
echo "  --machine-type=n2-highcpu-16 \\"
echo "  --accelerator=type=nvidia-tesla-t4,count=1 \\"
echo "  --boot-disk-size=200GB \\"
echo "  --boot-disk-type=pd-balanced \\"
echo "  --image-family=ubuntu-2204-lts \\"
echo "  --image-project=ubuntu-os-cloud \\"
echo "  --maintenance-policy=TERMINATE \\"
echo "  --metadata=install-nvidia-driver=True \\"
echo "  --scopes=cloud-platform"
echo ""

echo "Step 3: Set up the second instance"
echo "────────────────────────────────────────────────────────────────────"
echo "# SSH into ai-workspace-2 and run:"
echo "git clone https://github.com/YOUR_REPO/unity-ai.git"
echo "cd unity-ai"
echo "npm install"
echo "# Copy .env file from ai-workspace (DATABASE_URL, API keys, etc.)"
echo "npm run dev"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🔧 ONE-LINER FOR QUICK SETUP"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Upgrade instance 1 to n2-highcpu-16"
echo "gcloud compute instances stop $INSTANCE_NAME --zone=$ZONE --project=$PROJECT && \\"
echo "gcloud compute instances set-machine-type $INSTANCE_NAME --machine-type=n2-highcpu-16 --zone=$ZONE --project=$PROJECT && \\"
echo "gcloud compute instances start $INSTANCE_NAME --zone=$ZONE --project=$PROJECT"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🎮 HOW IT WORKS (Automatic Load Balancing)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Both instances connect to same Neon PostgreSQL database"
echo "✅ Both run job-worker.ts polling the jobs table"
echo "✅ Job status transitions prevent conflicts:"
echo "   • Instance 1 picks up Job A (queued → processing)"
echo "   • Instance 2 picks up Job B (queued → processing)"
echo "   • No double-processing!"
echo ""
echo "✅ Natural load distribution:"
echo "   • If 20 jobs queued → Instance 1 takes 10, Instance 2 takes 10"
echo "   • Each instance processes 8 jobs in parallel (MAX_CONCURRENT_JOBS=10)"
echo "   • Combined throughput: 16-20 jobs in parallel"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "💡 PRO TIPS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. Scale down when idle:"
echo "   • Stop instance 2 during low-traffic periods"
echo "   • Save ~50% cost on demand"
echo ""
echo "2. Redundancy:"
echo "   • If instance 1 crashes, instance 2 keeps working"
echo "   • No single point of failure"
echo ""
echo "3. Easy scaling:"
echo "   • Need more power? Add instance 3, 4, 5..."
echo "   • All share the same database and job queue"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "⚠️ IMPORTANT NOTES"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "• Both instances need the SAME .env file (DATABASE_URL, API keys)"
echo "• Only ONE frontend should be exposed (instance 1 at :8080)"
echo "• Instance 2 runs headless (just job-worker, no frontend)"
echo "• Both instances need nvidia-smi for GPU encoding"
echo "• Expected setup time: 20-30 minutes for instance 2"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "📊 COST BREAKDOWN"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Setup                      Monthly Cost    Speedup   Cost per vCPU"
echo "────────────────────────  ──────────────  ────────  ─────────────"
echo "1x n1-standard-8 (now)    \$240           1x        \$30/vCPU"
echo "2x n1-standard-8          \$480           2x        \$30/vCPU"
echo "2x n2-standard-8          \$400           2.3x      \$25/vCPU"
echo "2x n2-highcpu-16 ⭐       \$600           4x        \$18.75/vCPU"
echo "1x n2-highcpu-32          \$700           4.2x      \$21.88/vCPU"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🚀 Ready? Start with upgrading instance 1, then create instance 2!"
echo "═══════════════════════════════════════════════════════════════════"
